export const ADD_FAV = 'ADD_FAV'
export const REMOVE_FAV = 'REMOVE_FAV'
export const GET_FAV = 'GET_FAV'
export const ORDER_AND_FILTER = 'ORDER_AND_FILTER'
export const SET_USER = 'SET_USER'
export const RESET_FAVS = 'RESET_FAVS'